import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Banner from '../components/banner/banner'
import Navbar from '../components/nav/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>VS Videos Stream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner 
        title="Star Wars"
        subtitle="A new journey is comming!"
        imgUrl="/static/starWars.jpg"
      />
    </>
  )
}
