import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Banner from '../components/banner/banner'
import Navbar from '../components/nav/navbar'
import SectionCards from '../components/section-cards/section-cards'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const cards = [
    {
      title: "Disney",
      size: "large",
      cards: [
        {
          imgUrl: "/static/clifford.webp"
        },
        {
          imgUrl: "/static/clifford.webp"
        },
        {
          imgUrl: "/static/clifford.webp"
        }, 
        {
          imgUrl: "/static/clifford.webp"
        }, 
        {
          imgUrl: "/static/clifford.webp"
        },
        {
          imgUrl: "/static/clifford.webp"
        },
        {
          imgUrl: "/static/clifford.webp"
        },
        {
          imgUrl: "/static/clifford.webp"
        },
        {
          imgUrl: "/static/clifford.webp"
        }
      ]
    }
  ]

  return (
    <>
      <Head>
        <title>VS Videos Stream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner 
        title="Star Wars"
        subtitle="A new journey is comming!"
        imgUrl="/static/starWars.jpg"
      />
      {
        cards.map(section => (
          <SectionCards key={section.title} title={section.title} cards={section.cards} size={section.size} />
        ))
      }
    </>
  )
}
